apiVersion: v2
name: raft-storage
description: raft Storage
kubeVersion: ">=1.12.0"
type: application
version: 0.1.0
appVersion: v0.1.0-beta.1
keywords:
  - atomix
home: https://atomix.io
maintainers:
  - name: adib
    email: adib@opennetworking.org
  - name: kuujo
    email: jordan@opennetworking.org
